// TAC-OPS - material / mesh library
//
// Resolves an ETOMat id to a material in this order:
//   1. /Game/TacOps/Materials/Overrides/MO_<Name>   (artist supplied, e.g. a Megascans material)
//   2. Dynamic instance of /Game/TacOps/Materials/M_TO_Master (generated by Tools/setup_assets.py)
//   3. Dynamic instance of the engine BasicShapeMaterial (always available fallback)

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "Core/TOTypes.h"
#include "TOMaterialLibrary.generated.h"

class UMaterialInterface;
class UMaterialInstanceDynamic;
class UStaticMesh;

UENUM()
enum class ETOShape : uint8
{
	Cube,
	Cylinder,
	Sphere,
	Cone,
	Plane
};

struct FTOMatInfo
{
	const TCHAR* Name = TEXT("");
	FLinearColor Color = FLinearColor::White;
	float Roughness = 0.7f;
	float Metallic = 0.f;
	float Emissive = 0.f;
	/** 0 opaque, 1 glass, 2 water, 3 smoke, 4 unlit emissive */
	int32 Kind = 0;
	const TCHAR* Surface = TEXT("Concrete");
	float VertexColorAmount = 0.f;
};

UCLASS()
class TACOPS_API UTOMaterialLibrary : public UGameInstanceSubsystem
{
	GENERATED_BODY()

public:
	virtual void Initialize(FSubsystemCollectionBase& Collection) override;

	static UTOMaterialLibrary* Get(const UObject* WorldContext);

	UMaterialInterface* GetMaterial(ETOMat Mat);
	/** A unique dynamic instance (for things that animate their color/emissive). */
	UMaterialInstanceDynamic* MakeDynamic(ETOMat Mat);
	UStaticMesh* GetMesh(ETOShape Shape);

	static const FTOMatInfo& GetInfo(ETOMat Mat);
	static FName GetSurfaceTag(ETOMat Mat);

	/** True if the generated master material was found (better visuals). */
	bool HasGeneratedMaterials() const { return MasterMaterial != nullptr; }

	/** Sets a color on a dynamic instance created by this library, whatever its parent is. */
	static void SetDynamicColor(UMaterialInstanceDynamic* MID, const FLinearColor& Color, float Emissive = -1.f);

private:
	UPROPERTY() TObjectPtr<UMaterialInterface> MasterMaterial;
	UPROPERTY() TObjectPtr<UMaterialInterface> GlassMaterial;
	UPROPERTY() TObjectPtr<UMaterialInterface> WaterMaterial;
	UPROPERTY() TObjectPtr<UMaterialInterface> SmokeMaterial;
	UPROPERTY() TObjectPtr<UMaterialInterface> UnlitMaterial;
	UPROPERTY() TObjectPtr<UMaterialInterface> FallbackMaterial;

	UPROPERTY() TMap<uint8, TObjectPtr<UMaterialInterface>> Cache;
	UPROPERTY() TArray<TObjectPtr<UStaticMesh>> Meshes;
	UPROPERTY() TArray<TObjectPtr<UMaterialInstanceDynamic>> ExtraDynamics;

	UMaterialInterface* CreateFor(ETOMat Mat);
	UMaterialInterface* ParentFor(ETOMat Mat, bool& bOutIsMaster) const;
	void ApplyParams(UMaterialInstanceDynamic* MID, const FTOMatInfo& Info, bool bIsMaster) const;
};
